/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignRouteImport } from './routes/sign'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/_app/index'
import { Route as AuthedAppApprovalsRouteImport } from './routes/_authed/_app/approvals'
import { Route as AuthedAppBotRouteImport } from './routes/_authed/_app/bot'
import { Route as AuthedAppMemoryRouteImport } from './routes/_authed/_app/memory'
import { Route as AuthedAppReachabilityRouteImport } from './routes/_authed/_app/reachability'
import { Route as AuthedAppResponsibilitiesRouteImport } from './routes/_authed/_app/responsibilities'
import { Route as AuthedAppRoutinesRouteImport } from './routes/_authed/_app/routines'
import { Route as AuthedAppSettingsRouteRouteImport } from './routes/_authed/_app/settings/route'
import { Route as AuthedAppSkillsRouteImport } from './routes/_authed/_app/skills'
import { Route as AuthedAppTeamBotsRouteImport } from './routes/_authed/_app/team-bots'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed/admin/audit'
import { Route as AuthedAdminBoundariesRouteImport } from './routes/_authed/admin/boundaries'
import { Route as AuthedAdminComputersRouteImport } from './routes/_authed/admin/computers'
import { Route as AuthedAdminCredentialsRouteImport } from './routes/_authed/admin/credentials'
import { Route as AuthedAdminEnterpriseRouteImport } from './routes/_authed/admin/enterprise'
import { Route as AuthedAdminIdentityProvidersRouteImport } from './routes/_authed/admin/identity-providers'
import { Route as AuthedAdminLearningRouteImport } from './routes/_authed/admin/learning'
import { Route as AuthedAdminPeopleRouteImport } from './routes/_authed/admin/people'
import { Route as AuthedAdminPlaygroundRouteImport } from './routes/_authed/admin/playground'
import { Route as AuthedAdminSkillsRouteImport } from './routes/_authed/admin/skills'
import { Route as AuthedSignInRequestIdRouteImport } from './routes/_authed/sign-in/$requestId'
import { Route as AuthedAppAgentsIndexRouteImport } from './routes/_authed/_app/agents/index'
import { Route as AuthedAppBotsIndexRouteImport } from './routes/_authed/_app/bots.index'
import { Route as AuthedAppBotsAgentIdRouteImport } from './routes/_authed/_app/bots.$agentId'
import { Route as AuthedAppChannelChannelIdRouteImport } from './routes/_authed/_app/channel/$channelId'
import { Route as AuthedAppChannelNewRouteImport } from './routes/_authed/_app/channel/new'
import { Route as AuthedAppGroupChannelIdRouteImport } from './routes/_authed/_app/group/$channelId'
import { Route as AuthedAppGroupNewRouteImport } from './routes/_authed/_app/group/new'
import { Route as AuthedAppMarketplaceIndexRouteImport } from './routes/_authed/_app/marketplace/index'
import { Route as AuthedAppSettingsIndexRouteImport } from './routes/_authed/_app/settings/index'
import { Route as AuthedAppSettingsApprovalsRouteImport } from './routes/_authed/_app/settings/approvals'
import { Route as AuthedAppSettingsBotsRouteImport } from './routes/_authed/_app/settings/bots'
import { Route as AuthedAppSettingsMemoryRouteImport } from './routes/_authed/_app/settings/memory'
import { Route as AuthedAppSettingsNotificationsRouteImport } from './routes/_authed/_app/settings/notifications'
import { Route as AuthedAppSettingsPasswordsRouteImport } from './routes/_authed/_app/settings/passwords'
import { Route as AuthedAppSettingsUsageRouteImport } from './routes/_authed/_app/settings/usage'
import { Route as AuthedAdminComponentsIndexRouteImport } from './routes/_authed/admin/components/index'
import { Route as AuthedAdminComponentsNameRouteImport } from './routes/_authed/admin/components/$name'
import { Route as AuthedAdminPluginsIndexRouteImport } from './routes/_authed/admin/plugins/index'
import { Route as AuthedAdminPluginsKeyRouteImport } from './routes/_authed/admin/plugins/$key'
import { Route as AuthedAdminPluginsComposioRouteImport } from './routes/_authed/admin/plugins/composio'
import { Route as AuthedAppSettingsComponentsGalleryIndexRouteImport } from './routes/_authed/_app/settings/components-gallery/index'
import { Route as AuthedAppSettingsComponentsGalleryNameRouteImport } from './routes/_authed/_app/settings/components-gallery/$name'
import { Route as AuthedAppSettingsConnectedAccountsIndexRouteImport } from './routes/_authed/_app/settings/connected-accounts/index'
import { Route as AuthedAppSettingsConnectedAccountsKeyRouteImport } from './routes/_authed/_app/settings/connected-accounts/$key'
import { Route as AuthedAdminPluginsKeyBotsAgentIdRouteImport } from './routes/_authed/admin/plugins/$key_.bots.$agentId'
import { Route as AuthedAdminPluginsKeyToolsToolRouteImport } from './routes/_authed/admin/plugins/$key_.tools.$tool'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppApprovalsRoute = AuthedAppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppBotRoute = AuthedAppBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppMemoryRoute = AuthedAppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppReachabilityRoute = AuthedAppReachabilityRouteImport.update({
  id: '/reachability',
  path: '/reachability',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppResponsibilitiesRoute =
  AuthedAppResponsibilitiesRouteImport.update({
    id: '/responsibilities',
    path: '/responsibilities',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppRoutinesRoute = AuthedAppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSettingsRouteRoute = AuthedAppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSkillsRoute = AuthedAppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppTeamBotsRoute = AuthedAppTeamBotsRouteImport.update({
  id: '/team-bots',
  path: '/team-bots',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminBoundariesRoute = AuthedAdminBoundariesRouteImport.update({
  id: '/boundaries',
  path: '/boundaries',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminComputersRoute = AuthedAdminComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCredentialsRoute = AuthedAdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminEnterpriseRoute = AuthedAdminEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminIdentityProvidersRoute =
  AuthedAdminIdentityProvidersRouteImport.update({
    id: '/identity-providers',
    path: '/identity-providers',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminLearningRoute = AuthedAdminLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPeopleRoute = AuthedAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPlaygroundRoute = AuthedAdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminSkillsRoute = AuthedAdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedSignInRequestIdRoute = AuthedSignInRequestIdRouteImport.update({
  id: '/sign-in/$requestId',
  path: '/sign-in/$requestId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppAgentsIndexRoute = AuthedAppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppBotsIndexRoute = AuthedAppBotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppBotsAgentIdRoute = AuthedAppBotsAgentIdRouteImport.update({
  id: '/bots/$agentId',
  path: '/bots/$agentId',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppChannelChannelIdRoute =
  AuthedAppChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppChannelNewRoute = AuthedAppChannelNewRouteImport.update({
  id: '/channel/new',
  path: '/channel/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppGroupChannelIdRoute = AuthedAppGroupChannelIdRouteImport.update({
  id: '/group/$channelId',
  path: '/group/$channelId',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppGroupNewRoute = AuthedAppGroupNewRouteImport.update({
  id: '/group/new',
  path: '/group/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppMarketplaceIndexRoute =
  AuthedAppMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppSettingsIndexRoute = AuthedAppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppSettingsRouteRoute,
} as any)
const AuthedAppSettingsApprovalsRoute =
  AuthedAppSettingsApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthedAppSettingsRouteRoute,
  } as any)
const AuthedAppSettingsBotsRoute = AuthedAppSettingsBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthedAppSettingsRouteRoute,
} as any)
const AuthedAppSettingsMemoryRoute = AuthedAppSettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthedAppSettingsRouteRoute,
} as any)
const AuthedAppSettingsNotificationsRoute =
  AuthedAppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedAppSettingsRouteRoute,
  } as any)
const AuthedAppSettingsPasswordsRoute =
  AuthedAppSettingsPasswordsRouteImport.update({
    id: '/passwords',
    path: '/passwords',
    getParentRoute: () => AuthedAppSettingsRouteRoute,
  } as any)
const AuthedAppSettingsUsageRoute = AuthedAppSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthedAppSettingsRouteRoute,
} as any)
const AuthedAdminComponentsIndexRoute =
  AuthedAdminComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminComponentsNameRoute =
  AuthedAdminComponentsNameRouteImport.update({
    id: '/components/$name',
    path: '/components/$name',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminPluginsIndexRoute = AuthedAdminPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPluginsKeyRoute = AuthedAdminPluginsKeyRouteImport.update({
  id: '/plugins/$key',
  path: '/plugins/$key',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPluginsComposioRoute =
  AuthedAdminPluginsComposioRouteImport.update({
    id: '/plugins/composio',
    path: '/plugins/composio',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAppSettingsComponentsGalleryIndexRoute =
  AuthedAppSettingsComponentsGalleryIndexRouteImport.update({
    id: '/components-gallery/',
    path: '/components-gallery/',
    getParentRoute: () => AuthedAppSettingsRouteRoute,
  } as any)
const AuthedAppSettingsComponentsGalleryNameRoute =
  AuthedAppSettingsComponentsGalleryNameRouteImport.update({
    id: '/components-gallery/$name',
    path: '/components-gallery/$name',
    getParentRoute: () => AuthedAppSettingsRouteRoute,
  } as any)
const AuthedAppSettingsConnectedAccountsIndexRoute =
  AuthedAppSettingsConnectedAccountsIndexRouteImport.update({
    id: '/connected-accounts/',
    path: '/connected-accounts/',
    getParentRoute: () => AuthedAppSettingsRouteRoute,
  } as any)
const AuthedAppSettingsConnectedAccountsKeyRoute =
  AuthedAppSettingsConnectedAccountsKeyRouteImport.update({
    id: '/connected-accounts/$key',
    path: '/connected-accounts/$key',
    getParentRoute: () => AuthedAppSettingsRouteRoute,
  } as any)
const AuthedAdminPluginsKeyBotsAgentIdRoute =
  AuthedAdminPluginsKeyBotsAgentIdRouteImport.update({
    id: '/plugins/$key_/bots/$agentId',
    path: '/plugins/$key/bots/$agentId',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminPluginsKeyToolsToolRoute =
  AuthedAdminPluginsKeyToolsToolRouteImport.update({
    id: '/plugins/$key_/tools/$tool',
    path: '/plugins/$key/tools/$tool',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/settings': typeof AuthedAppSettingsRouteRouteWithChildren
  '/approvals': typeof AuthedAppApprovalsRoute
  '/bot': typeof AuthedAppBotRoute
  '/memory': typeof AuthedAppMemoryRoute
  '/reachability': typeof AuthedAppReachabilityRoute
  '/responsibilities': typeof AuthedAppResponsibilitiesRoute
  '/routines': typeof AuthedAppRoutinesRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/team-bots': typeof AuthedAppTeamBotsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/enterprise': typeof AuthedAdminEnterpriseRoute
  '/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/admin/learning': typeof AuthedAdminLearningRoute
  '/admin/people': typeof AuthedAdminPeopleRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/skills': typeof AuthedAdminSkillsRoute
  '/sign-in/$requestId': typeof AuthedSignInRequestIdRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/bots/$agentId': typeof AuthedAppBotsAgentIdRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/group/$channelId': typeof AuthedAppGroupChannelIdRoute
  '/group/new': typeof AuthedAppGroupNewRoute
  '/settings/approvals': typeof AuthedAppSettingsApprovalsRoute
  '/settings/bots': typeof AuthedAppSettingsBotsRoute
  '/settings/memory': typeof AuthedAppSettingsMemoryRoute
  '/settings/notifications': typeof AuthedAppSettingsNotificationsRoute
  '/settings/passwords': typeof AuthedAppSettingsPasswordsRoute
  '/settings/usage': typeof AuthedAppSettingsUsageRoute
  '/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/admin/plugins/composio': typeof AuthedAdminPluginsComposioRoute
  '/agents/': typeof AuthedAppAgentsIndexRoute
  '/bots/': typeof AuthedAppBotsIndexRoute
  '/marketplace/': typeof AuthedAppMarketplaceIndexRoute
  '/settings/': typeof AuthedAppSettingsIndexRoute
  '/admin/components/': typeof AuthedAdminComponentsIndexRoute
  '/admin/plugins/': typeof AuthedAdminPluginsIndexRoute
  '/settings/components-gallery/$name': typeof AuthedAppSettingsComponentsGalleryNameRoute
  '/settings/connected-accounts/$key': typeof AuthedAppSettingsConnectedAccountsKeyRoute
  '/settings/components-gallery/': typeof AuthedAppSettingsComponentsGalleryIndexRoute
  '/settings/connected-accounts/': typeof AuthedAppSettingsConnectedAccountsIndexRoute
  '/admin/plugins/$key/bots/$agentId': typeof AuthedAdminPluginsKeyBotsAgentIdRoute
  '/admin/plugins/$key/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/approvals': typeof AuthedAppApprovalsRoute
  '/bot': typeof AuthedAppBotRoute
  '/memory': typeof AuthedAppMemoryRoute
  '/reachability': typeof AuthedAppReachabilityRoute
  '/responsibilities': typeof AuthedAppResponsibilitiesRoute
  '/routines': typeof AuthedAppRoutinesRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/team-bots': typeof AuthedAppTeamBotsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/enterprise': typeof AuthedAdminEnterpriseRoute
  '/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/admin/learning': typeof AuthedAdminLearningRoute
  '/admin/people': typeof AuthedAdminPeopleRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/skills': typeof AuthedAdminSkillsRoute
  '/sign-in/$requestId': typeof AuthedSignInRequestIdRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/bots/$agentId': typeof AuthedAppBotsAgentIdRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/group/$channelId': typeof AuthedAppGroupChannelIdRoute
  '/group/new': typeof AuthedAppGroupNewRoute
  '/settings/approvals': typeof AuthedAppSettingsApprovalsRoute
  '/settings/bots': typeof AuthedAppSettingsBotsRoute
  '/settings/memory': typeof AuthedAppSettingsMemoryRoute
  '/settings/notifications': typeof AuthedAppSettingsNotificationsRoute
  '/settings/passwords': typeof AuthedAppSettingsPasswordsRoute
  '/settings/usage': typeof AuthedAppSettingsUsageRoute
  '/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/admin/plugins/composio': typeof AuthedAdminPluginsComposioRoute
  '/agents': typeof AuthedAppAgentsIndexRoute
  '/bots': typeof AuthedAppBotsIndexRoute
  '/marketplace': typeof AuthedAppMarketplaceIndexRoute
  '/settings': typeof AuthedAppSettingsIndexRoute
  '/admin/components': typeof AuthedAdminComponentsIndexRoute
  '/admin/plugins': typeof AuthedAdminPluginsIndexRoute
  '/settings/components-gallery/$name': typeof AuthedAppSettingsComponentsGalleryNameRoute
  '/settings/connected-accounts/$key': typeof AuthedAppSettingsConnectedAccountsKeyRoute
  '/settings/components-gallery': typeof AuthedAppSettingsComponentsGalleryIndexRoute
  '/settings/connected-accounts': typeof AuthedAppSettingsConnectedAccountsIndexRoute
  '/admin/plugins/$key/bots/$agentId': typeof AuthedAdminPluginsKeyBotsAgentIdRoute
  '/admin/plugins/$key/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign': typeof SignRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/_app/settings': typeof AuthedAppSettingsRouteRouteWithChildren
  '/_authed/_app/approvals': typeof AuthedAppApprovalsRoute
  '/_authed/_app/bot': typeof AuthedAppBotRoute
  '/_authed/_app/memory': typeof AuthedAppMemoryRoute
  '/_authed/_app/reachability': typeof AuthedAppReachabilityRoute
  '/_authed/_app/responsibilities': typeof AuthedAppResponsibilitiesRoute
  '/_authed/_app/routines': typeof AuthedAppRoutinesRoute
  '/_authed/_app/skills': typeof AuthedAppSkillsRoute
  '/_authed/_app/team-bots': typeof AuthedAppTeamBotsRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/_authed/admin/computers': typeof AuthedAdminComputersRoute
  '/_authed/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/_authed/admin/enterprise': typeof AuthedAdminEnterpriseRoute
  '/_authed/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/_authed/admin/learning': typeof AuthedAdminLearningRoute
  '/_authed/admin/people': typeof AuthedAdminPeopleRoute
  '/_authed/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/_authed/admin/skills': typeof AuthedAdminSkillsRoute
  '/_authed/sign-in/$requestId': typeof AuthedSignInRequestIdRoute
  '/_authed/_app/': typeof AuthedAppIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/_app/bots/$agentId': typeof AuthedAppBotsAgentIdRoute
  '/_authed/_app/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/_authed/_app/channel/new': typeof AuthedAppChannelNewRoute
  '/_authed/_app/group/$channelId': typeof AuthedAppGroupChannelIdRoute
  '/_authed/_app/group/new': typeof AuthedAppGroupNewRoute
  '/_authed/_app/settings/approvals': typeof AuthedAppSettingsApprovalsRoute
  '/_authed/_app/settings/bots': typeof AuthedAppSettingsBotsRoute
  '/_authed/_app/settings/memory': typeof AuthedAppSettingsMemoryRoute
  '/_authed/_app/settings/notifications': typeof AuthedAppSettingsNotificationsRoute
  '/_authed/_app/settings/passwords': typeof AuthedAppSettingsPasswordsRoute
  '/_authed/_app/settings/usage': typeof AuthedAppSettingsUsageRoute
  '/_authed/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/_authed/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/_authed/admin/plugins/composio': typeof AuthedAdminPluginsComposioRoute
  '/_authed/_app/agents/': typeof AuthedAppAgentsIndexRoute
  '/_authed/_app/bots/': typeof AuthedAppBotsIndexRoute
  '/_authed/_app/marketplace/': typeof AuthedAppMarketplaceIndexRoute
  '/_authed/_app/settings/': typeof AuthedAppSettingsIndexRoute
  '/_authed/admin/components/': typeof AuthedAdminComponentsIndexRoute
  '/_authed/admin/plugins/': typeof AuthedAdminPluginsIndexRoute
  '/_authed/_app/settings/components-gallery/$name': typeof AuthedAppSettingsComponentsGalleryNameRoute
  '/_authed/_app/settings/connected-accounts/$key': typeof AuthedAppSettingsConnectedAccountsKeyRoute
  '/_authed/_app/settings/components-gallery/': typeof AuthedAppSettingsComponentsGalleryIndexRoute
  '/_authed/_app/settings/connected-accounts/': typeof AuthedAppSettingsConnectedAccountsIndexRoute
  '/_authed/admin/plugins/$key_/bots/$agentId': typeof AuthedAdminPluginsKeyBotsAgentIdRoute
  '/_authed/admin/plugins/$key_/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign'
    | '/admin'
    | '/onboarding'
    | '/settings'
    | '/approvals'
    | '/bot'
    | '/memory'
    | '/reachability'
    | '/responsibilities'
    | '/routines'
    | '/skills'
    | '/team-bots'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/computers'
    | '/admin/credentials'
    | '/admin/enterprise'
    | '/admin/identity-providers'
    | '/admin/learning'
    | '/admin/people'
    | '/admin/playground'
    | '/admin/skills'
    | '/sign-in/$requestId'
    | '/admin/'
    | '/bots/$agentId'
    | '/channel/$channelId'
    | '/channel/new'
    | '/group/$channelId'
    | '/group/new'
    | '/settings/approvals'
    | '/settings/bots'
    | '/settings/memory'
    | '/settings/notifications'
    | '/settings/passwords'
    | '/settings/usage'
    | '/admin/components/$name'
    | '/admin/plugins/$key'
    | '/admin/plugins/composio'
    | '/agents/'
    | '/bots/'
    | '/marketplace/'
    | '/settings/'
    | '/admin/components/'
    | '/admin/plugins/'
    | '/settings/components-gallery/$name'
    | '/settings/connected-accounts/$key'
    | '/settings/components-gallery/'
    | '/settings/connected-accounts/'
    | '/admin/plugins/$key/bots/$agentId'
    | '/admin/plugins/$key/tools/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign'
    | '/onboarding'
    | '/approvals'
    | '/bot'
    | '/memory'
    | '/reachability'
    | '/responsibilities'
    | '/routines'
    | '/skills'
    | '/team-bots'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/computers'
    | '/admin/credentials'
    | '/admin/enterprise'
    | '/admin/identity-providers'
    | '/admin/learning'
    | '/admin/people'
    | '/admin/playground'
    | '/admin/skills'
    | '/sign-in/$requestId'
    | '/admin'
    | '/bots/$agentId'
    | '/channel/$channelId'
    | '/channel/new'
    | '/group/$channelId'
    | '/group/new'
    | '/settings/approvals'
    | '/settings/bots'
    | '/settings/memory'
    | '/settings/notifications'
    | '/settings/passwords'
    | '/settings/usage'
    | '/admin/components/$name'
    | '/admin/plugins/$key'
    | '/admin/plugins/composio'
    | '/agents'
    | '/bots'
    | '/marketplace'
    | '/settings'
    | '/admin/components'
    | '/admin/plugins'
    | '/settings/components-gallery/$name'
    | '/settings/connected-accounts/$key'
    | '/settings/components-gallery'
    | '/settings/connected-accounts'
    | '/admin/plugins/$key/bots/$agentId'
    | '/admin/plugins/$key/tools/$tool'
  id:
    | '__root__'
    | '/_authed'
    | '/sign'
    | '/_authed/admin'
    | '/_authed/_app'
    | '/_authed/onboarding'
    | '/_authed/_app/settings'
    | '/_authed/_app/approvals'
    | '/_authed/_app/bot'
    | '/_authed/_app/memory'
    | '/_authed/_app/reachability'
    | '/_authed/_app/responsibilities'
    | '/_authed/_app/routines'
    | '/_authed/_app/skills'
    | '/_authed/_app/team-bots'
    | '/_authed/admin/audit'
    | '/_authed/admin/boundaries'
    | '/_authed/admin/computers'
    | '/_authed/admin/credentials'
    | '/_authed/admin/enterprise'
    | '/_authed/admin/identity-providers'
    | '/_authed/admin/learning'
    | '/_authed/admin/people'
    | '/_authed/admin/playground'
    | '/_authed/admin/skills'
    | '/_authed/sign-in/$requestId'
    | '/_authed/_app/'
    | '/_authed/admin/'
    | '/_authed/_app/bots/$agentId'
    | '/_authed/_app/channel/$channelId'
    | '/_authed/_app/channel/new'
    | '/_authed/_app/group/$channelId'
    | '/_authed/_app/group/new'
    | '/_authed/_app/settings/approvals'
    | '/_authed/_app/settings/bots'
    | '/_authed/_app/settings/memory'
    | '/_authed/_app/settings/notifications'
    | '/_authed/_app/settings/passwords'
    | '/_authed/_app/settings/usage'
    | '/_authed/admin/components/$name'
    | '/_authed/admin/plugins/$key'
    | '/_authed/admin/plugins/composio'
    | '/_authed/_app/agents/'
    | '/_authed/_app/bots/'
    | '/_authed/_app/marketplace/'
    | '/_authed/_app/settings/'
    | '/_authed/admin/components/'
    | '/_authed/admin/plugins/'
    | '/_authed/_app/settings/components-gallery/$name'
    | '/_authed/_app/settings/connected-accounts/$key'
    | '/_authed/_app/settings/components-gallery/'
    | '/_authed/_app/settings/connected-accounts/'
    | '/_authed/admin/plugins/$key_/bots/$agentId'
    | '/_authed/admin/plugins/$key_/tools/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/': {
      id: '/_authed/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/approvals': {
      id: '/_authed/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthedAppApprovalsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/bot': {
      id: '/_authed/_app/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthedAppBotRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/memory': {
      id: '/_authed/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthedAppMemoryRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/reachability': {
      id: '/_authed/_app/reachability'
      path: '/reachability'
      fullPath: '/reachability'
      preLoaderRoute: typeof AuthedAppReachabilityRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/responsibilities': {
      id: '/_authed/_app/responsibilities'
      path: '/responsibilities'
      fullPath: '/responsibilities'
      preLoaderRoute: typeof AuthedAppResponsibilitiesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/routines': {
      id: '/_authed/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AuthedAppRoutinesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/settings': {
      id: '/_authed/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedAppSettingsRouteRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/skills': {
      id: '/_authed/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthedAppSkillsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/team-bots': {
      id: '/_authed/_app/team-bots'
      path: '/team-bots'
      fullPath: '/team-bots'
      preLoaderRoute: typeof AuthedAppTeamBotsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/boundaries': {
      id: '/_authed/admin/boundaries'
      path: '/boundaries'
      fullPath: '/admin/boundaries'
      preLoaderRoute: typeof AuthedAdminBoundariesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/computers': {
      id: '/_authed/admin/computers'
      path: '/computers'
      fullPath: '/admin/computers'
      preLoaderRoute: typeof AuthedAdminComputersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/credentials': {
      id: '/_authed/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthedAdminCredentialsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/enterprise': {
      id: '/_authed/admin/enterprise'
      path: '/enterprise'
      fullPath: '/admin/enterprise'
      preLoaderRoute: typeof AuthedAdminEnterpriseRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/identity-providers': {
      id: '/_authed/admin/identity-providers'
      path: '/identity-providers'
      fullPath: '/admin/identity-providers'
      preLoaderRoute: typeof AuthedAdminIdentityProvidersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/learning': {
      id: '/_authed/admin/learning'
      path: '/learning'
      fullPath: '/admin/learning'
      preLoaderRoute: typeof AuthedAdminLearningRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/people': {
      id: '/_authed/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthedAdminPeopleRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/playground': {
      id: '/_authed/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AuthedAdminPlaygroundRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/skills': {
      id: '/_authed/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthedAdminSkillsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/sign-in/$requestId': {
      id: '/_authed/sign-in/$requestId'
      path: '/sign-in/$requestId'
      fullPath: '/sign-in/$requestId'
      preLoaderRoute: typeof AuthedSignInRequestIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/agents/': {
      id: '/_authed/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAppAgentsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/bots/': {
      id: '/_authed/_app/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof AuthedAppBotsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/bots/$agentId': {
      id: '/_authed/_app/bots/$agentId'
      path: '/bots/$agentId'
      fullPath: '/bots/$agentId'
      preLoaderRoute: typeof AuthedAppBotsAgentIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/$channelId': {
      id: '/_authed/_app/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthedAppChannelChannelIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/new': {
      id: '/_authed/_app/channel/new'
      path: '/channel/new'
      fullPath: '/channel/new'
      preLoaderRoute: typeof AuthedAppChannelNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/group/$channelId': {
      id: '/_authed/_app/group/$channelId'
      path: '/group/$channelId'
      fullPath: '/group/$channelId'
      preLoaderRoute: typeof AuthedAppGroupChannelIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/group/new': {
      id: '/_authed/_app/group/new'
      path: '/group/new'
      fullPath: '/group/new'
      preLoaderRoute: typeof AuthedAppGroupNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/marketplace/': {
      id: '/_authed/_app/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthedAppMarketplaceIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/settings/': {
      id: '/_authed/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedAppSettingsIndexRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/approvals': {
      id: '/_authed/_app/settings/approvals'
      path: '/approvals'
      fullPath: '/settings/approvals'
      preLoaderRoute: typeof AuthedAppSettingsApprovalsRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/bots': {
      id: '/_authed/_app/settings/bots'
      path: '/bots'
      fullPath: '/settings/bots'
      preLoaderRoute: typeof AuthedAppSettingsBotsRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/memory': {
      id: '/_authed/_app/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof AuthedAppSettingsMemoryRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/notifications': {
      id: '/_authed/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedAppSettingsNotificationsRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/passwords': {
      id: '/_authed/_app/settings/passwords'
      path: '/passwords'
      fullPath: '/settings/passwords'
      preLoaderRoute: typeof AuthedAppSettingsPasswordsRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/usage': {
      id: '/_authed/_app/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof AuthedAppSettingsUsageRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/admin/components/': {
      id: '/_authed/admin/components/'
      path: '/components'
      fullPath: '/admin/components/'
      preLoaderRoute: typeof AuthedAdminComponentsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/components/$name': {
      id: '/_authed/admin/components/$name'
      path: '/components/$name'
      fullPath: '/admin/components/$name'
      preLoaderRoute: typeof AuthedAdminComponentsNameRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins/': {
      id: '/_authed/admin/plugins/'
      path: '/plugins'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AuthedAdminPluginsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins/$key': {
      id: '/_authed/admin/plugins/$key'
      path: '/plugins/$key'
      fullPath: '/admin/plugins/$key'
      preLoaderRoute: typeof AuthedAdminPluginsKeyRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins/composio': {
      id: '/_authed/admin/plugins/composio'
      path: '/plugins/composio'
      fullPath: '/admin/plugins/composio'
      preLoaderRoute: typeof AuthedAdminPluginsComposioRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/_app/settings/components-gallery/': {
      id: '/_authed/_app/settings/components-gallery/'
      path: '/components-gallery'
      fullPath: '/settings/components-gallery/'
      preLoaderRoute: typeof AuthedAppSettingsComponentsGalleryIndexRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/components-gallery/$name': {
      id: '/_authed/_app/settings/components-gallery/$name'
      path: '/components-gallery/$name'
      fullPath: '/settings/components-gallery/$name'
      preLoaderRoute: typeof AuthedAppSettingsComponentsGalleryNameRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/connected-accounts/': {
      id: '/_authed/_app/settings/connected-accounts/'
      path: '/connected-accounts'
      fullPath: '/settings/connected-accounts/'
      preLoaderRoute: typeof AuthedAppSettingsConnectedAccountsIndexRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/_app/settings/connected-accounts/$key': {
      id: '/_authed/_app/settings/connected-accounts/$key'
      path: '/connected-accounts/$key'
      fullPath: '/settings/connected-accounts/$key'
      preLoaderRoute: typeof AuthedAppSettingsConnectedAccountsKeyRouteImport
      parentRoute: typeof AuthedAppSettingsRouteRoute
    }
    '/_authed/admin/plugins/$key_/bots/$agentId': {
      id: '/_authed/admin/plugins/$key_/bots/$agentId'
      path: '/plugins/$key/bots/$agentId'
      fullPath: '/admin/plugins/$key/bots/$agentId'
      preLoaderRoute: typeof AuthedAdminPluginsKeyBotsAgentIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins/$key_/tools/$tool': {
      id: '/_authed/admin/plugins/$key_/tools/$tool'
      path: '/plugins/$key/tools/$tool'
      fullPath: '/admin/plugins/$key/tools/$tool'
      preLoaderRoute: typeof AuthedAdminPluginsKeyToolsToolRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminBoundariesRoute: typeof AuthedAdminBoundariesRoute
  AuthedAdminComputersRoute: typeof AuthedAdminComputersRoute
  AuthedAdminCredentialsRoute: typeof AuthedAdminCredentialsRoute
  AuthedAdminEnterpriseRoute: typeof AuthedAdminEnterpriseRoute
  AuthedAdminIdentityProvidersRoute: typeof AuthedAdminIdentityProvidersRoute
  AuthedAdminLearningRoute: typeof AuthedAdminLearningRoute
  AuthedAdminPeopleRoute: typeof AuthedAdminPeopleRoute
  AuthedAdminPlaygroundRoute: typeof AuthedAdminPlaygroundRoute
  AuthedAdminSkillsRoute: typeof AuthedAdminSkillsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminComponentsNameRoute: typeof AuthedAdminComponentsNameRoute
  AuthedAdminPluginsKeyRoute: typeof AuthedAdminPluginsKeyRoute
  AuthedAdminPluginsComposioRoute: typeof AuthedAdminPluginsComposioRoute
  AuthedAdminComponentsIndexRoute: typeof AuthedAdminComponentsIndexRoute
  AuthedAdminPluginsIndexRoute: typeof AuthedAdminPluginsIndexRoute
  AuthedAdminPluginsKeyBotsAgentIdRoute: typeof AuthedAdminPluginsKeyBotsAgentIdRoute
  AuthedAdminPluginsKeyToolsToolRoute: typeof AuthedAdminPluginsKeyToolsToolRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminBoundariesRoute: AuthedAdminBoundariesRoute,
  AuthedAdminComputersRoute: AuthedAdminComputersRoute,
  AuthedAdminCredentialsRoute: AuthedAdminCredentialsRoute,
  AuthedAdminEnterpriseRoute: AuthedAdminEnterpriseRoute,
  AuthedAdminIdentityProvidersRoute: AuthedAdminIdentityProvidersRoute,
  AuthedAdminLearningRoute: AuthedAdminLearningRoute,
  AuthedAdminPeopleRoute: AuthedAdminPeopleRoute,
  AuthedAdminPlaygroundRoute: AuthedAdminPlaygroundRoute,
  AuthedAdminSkillsRoute: AuthedAdminSkillsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminComponentsNameRoute: AuthedAdminComponentsNameRoute,
  AuthedAdminPluginsKeyRoute: AuthedAdminPluginsKeyRoute,
  AuthedAdminPluginsComposioRoute: AuthedAdminPluginsComposioRoute,
  AuthedAdminComponentsIndexRoute: AuthedAdminComponentsIndexRoute,
  AuthedAdminPluginsIndexRoute: AuthedAdminPluginsIndexRoute,
  AuthedAdminPluginsKeyBotsAgentIdRoute: AuthedAdminPluginsKeyBotsAgentIdRoute,
  AuthedAdminPluginsKeyToolsToolRoute: AuthedAdminPluginsKeyToolsToolRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedAppSettingsRouteRouteChildren {
  AuthedAppSettingsApprovalsRoute: typeof AuthedAppSettingsApprovalsRoute
  AuthedAppSettingsBotsRoute: typeof AuthedAppSettingsBotsRoute
  AuthedAppSettingsMemoryRoute: typeof AuthedAppSettingsMemoryRoute
  AuthedAppSettingsNotificationsRoute: typeof AuthedAppSettingsNotificationsRoute
  AuthedAppSettingsPasswordsRoute: typeof AuthedAppSettingsPasswordsRoute
  AuthedAppSettingsUsageRoute: typeof AuthedAppSettingsUsageRoute
  AuthedAppSettingsIndexRoute: typeof AuthedAppSettingsIndexRoute
  AuthedAppSettingsComponentsGalleryNameRoute: typeof AuthedAppSettingsComponentsGalleryNameRoute
  AuthedAppSettingsConnectedAccountsKeyRoute: typeof AuthedAppSettingsConnectedAccountsKeyRoute
  AuthedAppSettingsComponentsGalleryIndexRoute: typeof AuthedAppSettingsComponentsGalleryIndexRoute
  AuthedAppSettingsConnectedAccountsIndexRoute: typeof AuthedAppSettingsConnectedAccountsIndexRoute
}

const AuthedAppSettingsRouteRouteChildren: AuthedAppSettingsRouteRouteChildren =
  {
    AuthedAppSettingsApprovalsRoute: AuthedAppSettingsApprovalsRoute,
    AuthedAppSettingsBotsRoute: AuthedAppSettingsBotsRoute,
    AuthedAppSettingsMemoryRoute: AuthedAppSettingsMemoryRoute,
    AuthedAppSettingsNotificationsRoute: AuthedAppSettingsNotificationsRoute,
    AuthedAppSettingsPasswordsRoute: AuthedAppSettingsPasswordsRoute,
    AuthedAppSettingsUsageRoute: AuthedAppSettingsUsageRoute,
    AuthedAppSettingsIndexRoute: AuthedAppSettingsIndexRoute,
    AuthedAppSettingsComponentsGalleryNameRoute:
      AuthedAppSettingsComponentsGalleryNameRoute,
    AuthedAppSettingsConnectedAccountsKeyRoute:
      AuthedAppSettingsConnectedAccountsKeyRoute,
    AuthedAppSettingsComponentsGalleryIndexRoute:
      AuthedAppSettingsComponentsGalleryIndexRoute,
    AuthedAppSettingsConnectedAccountsIndexRoute:
      AuthedAppSettingsConnectedAccountsIndexRoute,
  }

const AuthedAppSettingsRouteRouteWithChildren =
  AuthedAppSettingsRouteRoute._addFileChildren(
    AuthedAppSettingsRouteRouteChildren,
  )

interface AuthedAppRouteChildren {
  AuthedAppSettingsRouteRoute: typeof AuthedAppSettingsRouteRouteWithChildren
  AuthedAppApprovalsRoute: typeof AuthedAppApprovalsRoute
  AuthedAppBotRoute: typeof AuthedAppBotRoute
  AuthedAppMemoryRoute: typeof AuthedAppMemoryRoute
  AuthedAppReachabilityRoute: typeof AuthedAppReachabilityRoute
  AuthedAppResponsibilitiesRoute: typeof AuthedAppResponsibilitiesRoute
  AuthedAppRoutinesRoute: typeof AuthedAppRoutinesRoute
  AuthedAppSkillsRoute: typeof AuthedAppSkillsRoute
  AuthedAppTeamBotsRoute: typeof AuthedAppTeamBotsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppBotsAgentIdRoute: typeof AuthedAppBotsAgentIdRoute
  AuthedAppChannelChannelIdRoute: typeof AuthedAppChannelChannelIdRoute
  AuthedAppChannelNewRoute: typeof AuthedAppChannelNewRoute
  AuthedAppGroupChannelIdRoute: typeof AuthedAppGroupChannelIdRoute
  AuthedAppGroupNewRoute: typeof AuthedAppGroupNewRoute
  AuthedAppAgentsIndexRoute: typeof AuthedAppAgentsIndexRoute
  AuthedAppBotsIndexRoute: typeof AuthedAppBotsIndexRoute
  AuthedAppMarketplaceIndexRoute: typeof AuthedAppMarketplaceIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppSettingsRouteRoute: AuthedAppSettingsRouteRouteWithChildren,
  AuthedAppApprovalsRoute: AuthedAppApprovalsRoute,
  AuthedAppBotRoute: AuthedAppBotRoute,
  AuthedAppMemoryRoute: AuthedAppMemoryRoute,
  AuthedAppReachabilityRoute: AuthedAppReachabilityRoute,
  AuthedAppResponsibilitiesRoute: AuthedAppResponsibilitiesRoute,
  AuthedAppRoutinesRoute: AuthedAppRoutinesRoute,
  AuthedAppSkillsRoute: AuthedAppSkillsRoute,
  AuthedAppTeamBotsRoute: AuthedAppTeamBotsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppBotsAgentIdRoute: AuthedAppBotsAgentIdRoute,
  AuthedAppChannelChannelIdRoute: AuthedAppChannelChannelIdRoute,
  AuthedAppChannelNewRoute: AuthedAppChannelNewRoute,
  AuthedAppGroupChannelIdRoute: AuthedAppGroupChannelIdRoute,
  AuthedAppGroupNewRoute: AuthedAppGroupNewRoute,
  AuthedAppAgentsIndexRoute: AuthedAppAgentsIndexRoute,
  AuthedAppBotsIndexRoute: AuthedAppBotsIndexRoute,
  AuthedAppMarketplaceIndexRoute: AuthedAppMarketplaceIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedSignInRequestIdRoute: typeof AuthedSignInRequestIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedSignInRequestIdRoute: AuthedSignInRequestIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
