import { mkdir, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, resolve } from "node:path";
import {
  createApplicationConfiguration,
  loadTenantPackage,
} from "../server/src/tenant-package";

const projectRoot = resolve(import.meta.dir, "..");
const configuredTenantPackageDirectory = process.env.TENANT_PACKAGE_DIR;
const tenantPackageDirectory = configuredTenantPackageDirectory
  ? isAbsolute(configuredTenantPackageDirectory)
    ? configuredTenantPackageDirectory
    : resolve(projectRoot, "server", configuredTenantPackageDirectory)
  : resolve(projectRoot, "examples/noebot");
const tenantPackage = await loadTenantPackage(tenantPackageDirectory);
const applicationConfiguration = createApplicationConfiguration(tenantPackage);
const outputPath = resolve(
  projectRoot,
  "app/src/lib/generated/application-config.ts",
);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    "// This file is generated by scripts/generate-app-config.ts. Do not edit it.",
    "export type AppConfig = { brand: { tenantId: string; productName: string } };",
    `export const appConfig: AppConfig = ${JSON.stringify(applicationConfiguration, null, 2)};`,
    "",
  ].join("\n"),
);
